# Generated by Django 2.2.10 on 2021-05-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0002_auto_20210511_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls_api.Polls', verbose_name='Опрос'),
        ),
    ]
