# Generated by Django 2.2.10 on 2021-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0004_auto_20210512_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroptions',
            name='question',
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='question',
            field=models.ManyToManyField(to='polls_api.Questions', verbose_name='Вопрос'),
        ),
    ]
