# Generated by Django 2.2.10 on 2021-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0005_auto_20210512_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='question',
            field=models.ManyToManyField(related_name='answer_options', to='polls_api.Questions', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='poll',
            field=models.ManyToManyField(related_name='questions', to='polls_api.Polls', verbose_name='Опрос'),
        ),
    ]
