# Generated by Django 2.2.10 on 2021-05-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0007_auto_20210512_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroptions',
            name='question',
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='polls_api.Questions', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='questions',
            name='poll',
        ),
        migrations.AddField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls_api.Polls', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
