# Generated by Django 2.2.10 on 2021-05-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0012_auto_20210512_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текстовый ответ'),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_api.AnswerOptions', verbose_name='Ответ'),
        ),
    ]
