# Generated by Django 2.2.10 on 2021-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0013_auto_20210512_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер вопроса'),
        ),
    ]
