# Generated by Django 2.2.10 on 2021-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0015_answeroptions_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер вопроса'),
        ),
    ]
