# Generated by Django 2.2.10 on 2021-05-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0016_auto_20210513_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовый ответ'),
        ),
    ]
